language: php

php:
  - 7.0
  - 7.1

env:
  - ENCRYPTION_KEY=3dd1c15c3e4f0fd3c100e12748312405a1285b091e05349151ad4a7f92ea0f20

before_script:
  - composer self-update
  - composer install
  - composer dump-autoload -o
  - chmod -R 755 resources
  - chmod -R 755 tmp
  - php apex api
  - php apex docs

script: vendor/bin/phpunit --verbose

notifications:
  email:
    - dbyoung2@gmail.com

sudo: false

matrix:
  allow_failures:
    - php: 7.1
  fast_finish: true