language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install
  - composer dump-autoload -o

script: vendor/bin/phpunit --verbose

notifications:
  email:
    - dbyoung2@gmail.com

matrix:
  fast_finish: true