language: php

php:
  - 7.1

# Deploy the key to tmp so that it doesn't get deployed by accident
before_install:
  - openssl aes-256-cbc -K $encrypted_9e0079ced4d6_key -iv $encrypted_9e0079ced4d6_iv -in ./bin/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

install:
  - echo '|1|G/4KNvEcGF2Z9aQlhAPGx7Q209A=|fDHcHFGSaDw4EapQIj60uB56UQw= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2sXlPCPRtUQ1/zjVFtwi5DAYFZqb1uCEXeRZRMrk4rcn2fp01w7vX9YSHaB+0Uvt9Mf9inygsOEFvo8Zf965tQ9ME3oEm1b8jg0SmU1NGnwAVkBr+2yoCTPbecE2gCFK2gi+dw8Fu4+pVIxM0/AbSPmvQLNJ4Fbk0JulvJ9VwQnGJ4rZeMOlNAVYA4qs7dWNmNCpAGcDmCfiNRHFQKghFQXYOvk2DGN/3BhCCr1tjA9lNhalMI+bB4Wx3WSmaxww8BFVV8mSHVKaXcHdjEFbBt5JK0YMIAf/4JKJHD2V5ue8lpVZa1p0N+4yp9NCFudcYB42ww0wAONbulM0SDKgT' >> $HOME/.ssh/known_hosts

git:
  depth: false

env:
  - ENCRYPTION_KEY=3dd1c15c3e4f0fd3c100e12748312405a1285b091e05349151ad4a7f92ea0f20

before_script:
  - composer self-update
  - composer install
  - composer dump-autoload -o
  - chmod -R 755 resources
  - chmod -R 755 tmp
  - php apex compile:api
  - php apex compile:docs
  - php apex framework:flushcache

script: vendor/bin/phpunit --verbose

deploy:
  - provider: script
    script: bash bin/deploy.sh $TRAVIS_BUILD_DIR $TRAVIS_JOB_NUMBER $SSH_USER $SSH_HOST
    on:
      branch: "1.0"
    skip_cleanup: true

notifications:
  email:
    recipients:
      - dbyoung2@gmail.com
    on_success: always

sudo: false

matrix:
  fast_finish: true
